name: Build

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-18.04
    env:
      JAVA_HOME: /usr/lib/jvm/zulu-12-azure-amd64
      GIT_REF: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          login-server: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: mvn --no-transfer-progress clean package -Dmaven.test.skip=true
      - run: make docker-push
      - run: make docker-push TAG=${GITHUB_SHA:0:8}
