name: Maven build

on: [push]

jobs:
  build:
    name: Hello
    runs-on: ubuntu-18.04
    env:
      JAVA_HOME: /usr/lib/jvm/zulu-12-azure-amd64
    steps:
      - uses: actions/checkout@v1
      - run: mvn -version
      - run: mvn clean package
